### ISSUE TITLE
Build error npm stall -- message "Uncaught RangeError: maximumFractionDigits value is out of range." in console

### ISSUE THREAD

**Issue by gness1804** [open-austin/budgetparty#111]
When attempting to start a dev server, the build fails for me with a blank screen on localhost:3000. In the console, a red error appears as follows: "Uncaught RangeError: maximumFractionDigits value is out of range."

Even after installing the missing dependencies as noted in issue #109 , and doing an npm install and npm run build, this error persists. 

Screenshot below. 

<img width="1280" alt="screen shot 2017-05-10 at 8 23 37 pm" src="https://cloud.githubusercontent.com/assets/17103851/25928184/6d966aa8-35c0-11e7-8603-6c188c4d5049.png">

@mateoclarke

**Comment by mateoclarke** [comment]
Oof, let me debug that and push new code. Sorry this blew up on you and 👍  for letting me know with this screenshot. 

_i suck at computers_

**Comment by drewpchannel** [comment]
My version runs but still gets this error

http://imgur.com/a/BpjJw

**Comment by mateoclarke** [comment]
I just pushed two commits that I hope resolve this bug. I think the problem was that I was using the `new Intl.NumberFormat` constructor as recommended by [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) here instead of the react-intl's `<FormattedNumber>` component.

@drewpchannel's error looked like a propType (different but related) so I changed the proptypes to expect a number instead of a string.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

Please let me know if this is still buggy. 

Thanks y'all!!!!
