### ISSUE TITLE
Missing Department?

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/budgetparty#121]
Should Economic Development be under "development"
https://data.austintexas.gov/stories/s/Economic-Development/upmt-be6h

**Comment by mateoclarke** [comment]
Yeah it seems like you're right that it's missing. I wonder if it was left out on purpose? Maybe they don't get funding from the General Fund? This would be a question for @sya or @graceatkins or another budget wonk.

**Comment by graceatkins** [comment]
I'll look into it. I vaguely remember one of two reasons it's not included but I'll double check the explanation. It's either that is not general fund money (I vaguely remember there being a discussion about it coming from Austin Energy and AW) it could also be another funding change from year to year. I'll let y'all know!

**Comment by graceatkins** [comment]
@mateoclarke @VictoriaODell Hey Guys I just looked it up, and it is not included because the department is not technically funded directly from the general fund. It is funded by Austin Energy and Austin Water, etc through direct transfers. This is separate from the more general transfers from AE and AW to the general fund at large. 

The justification for these smaller, more direct transfers is the economic development aspects would be part of the larger businesses operations, but instead of each company having a separate economic development division it is all funneled into the city's larger economic development umbrella. Lemme know if that doesnt make sense!
