### ISSUE TITLE
Update Anonoymous Auth to the Firebase way

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#132]
Right now, when a user clicks Skip Login, we just send them to the next route. We should do anonymous auth at that point instead.

https://firebase.google.com/docs/auth/web/anonymous-auth

**Comment by smonami** [comment]
Code design question:

First approach
  
- new function in auth.js: annonymous_auth, call firebase's annonymous login.
- new handler in AuthForm, handleSkipLogin and call annonymous_auth
- Invoke handleSkipLogin of AuthForm from Home
- update error state as in handleLogin.

issue: Link is defined outside Tab and so not part of the AuthForm and so will require some UI design changes.

Second approach:

- new function in auth.js: annonymous_auth, call firebase's annonymous login. 
- new onClick  in Home skipLogin and call annonymous_auth from auth.
- issue: We are spreading auth related logic in multiple components.
- What to do in error case?


What do you suggest? Any of the above or any other design?

**Comment by mateoclarke** [comment]
@smonami, this is a very thoughtful comment. Thank you!

If I follow your suggestion for the first approach, the issue around having to reorganize which components can perform with function doesn't sound like a deal breaker to me. At our hack night tonight, there was some discussion around how we might refactor the Home component. cc/ @grewp

I don't follow as clearly the issue with the second approach. Particularly error handling. But forgive me.

Maybe to put it in different words... 
The `Home` component is parent to the `AuthForm` component. But with the Skip Login link now having the effect of providing anonymous authentication, the concern of handling authentication that used to live in AuthForm should belong to Home. 

So we could:
1. New function in auth.js called `annonymous_auth`, which calls firebase's annonymous login.
1. Move the existing handlers from AuthForm to Home in addition to the new `handleSkipLogin`
1. Invoke `handleSkipLogin` onClick for Skip Login link.
1. Rename AuthForm to "LoginForm". Rename Home to "AuthLogin" (open to better names)

Are we on the same page?

**Comment by smonami** [comment]
@mateoclarke Thanks! I started coding based on what you suggested. I like this parent/child data flow design so we are on the same page.
For:
> 4. Rename AuthForm to "LoginForm". Rename Home to "AuthLogin" (open to better names)

I have no better suggestion for the names, so I will submit the pull request with these component names for now. But feel free to suggest other names if you can think of something else in between.

**Comment by smonami** [comment]
@mateoclarke just realized, if we change component names, our CSS class names would go out of sync, for e.g. all the classes inside AuthForm use "auth-form" for the class names. 
I think it is "ok" to keep the same names for the components and just refactor the functionality.

**Comment by mateoclarke** [comment]
Yeah, good point about the CSS class names. I was trying to follow the BEM pattern, where the B (block) is the component name. This does make any wholesale refactoring a bit annoying. So yeah, I wouldn't worry about changing the name. We can tackle that in a later refactoring if/when it gets too confusing.

**Comment by grewp** [comment]
Sorry for the late reply, but a couple of thoughts on this.

I think both of @smonami's suggestions are valid approaches, but the problem of deciding between the two of them points to a larger issue with inconsistency in how we handle logins.

1. I think the way we currently have the components set up with each method of logging in appearing in separate components (AuthForm.js, GoogleAuth.js, and Home.js [which also calls the aforementioned components]) is a bit clunky and difficult to navigate. I propose we refactor and create a **unified login component** with methods to handle each of the three possible options.
2. More importantly (and this will also make part 1 easier) is that I've noticed we perform authentication by calling firebase's authentication methods directly in these components. I think this approach could be dangerous because it means having to maintain proper authentication in each different implementation in a growing number of ways as we continue to develop the app. Instead, I suggest we move all of the firebase behavior to a single reducer. The component handlers will now simply dispatch actions, and the reducer will handle calling these API's. If authentication was a success, we can then call `setState({ authed: true })` in the reducer and for the rest of our app, we only have to worry if the global auth object is true, regardless of how a user logged in.

Hopefully the above changes can help us simplify the login architecture and will make it easier to start implementing more robust firebase functionality. I am going to fork a branch today and start playing around with the code to see if I can get this up and running without breaking things. @mateoclarke what do you think?

**Comment by mateoclarke** [comment]
That all sounds good @grewp!

**Comment by grewp** [comment]
Hmm, looks like this isn't as straightforward as I thought because of the way Firebase handles authentication by using a global listener that's started on App mount. Additionally, it looks like my idea of moving authentication to the reducer is anti-pattern; instead we should be moving them to *actions*. However, I think it'll be worth the trouble for the chance to make the codebase more consistent.

Luckily, it looks like there's a great [tutorial](http://blog.krawaller.se/posts/a-react-redux-firebase-app-with-authentication/) on integrating a React-Redux-Firebase app. I'll start to go through this and see what we can do.

**Comment by smonami** [comment]
Pull request submitted. https://github.com/open-austin/budgetparty/pull/186

**Comment by mateoclarke** [comment]
Think this is closed now, but please reopen if there is more discussion or more to do.
