### ISSUE TITLE
Updated Budget from Proposed to Approved Numbers

### ISSUE THREAD

**Issue by sya** [open-austin/budgetparty#157]
Source for ACCURATE NUMBERS>>> 
https://www.austintexas.gov/financeonline/finance/budget/department.cfm

Reaching out to COA to discuss Public Works numbers

**Comment by mateoclarke** [comment]
@graceatkins and I started digging through more sources of budget data tonight. She shared her process from last year for gathering the original numbers. It is became very clear that there are several options but no sure way to get Department Budget allocations specifically from the General Fund. 

We started this Sheet for collaboration.
https://docs.google.com/spreadsheets/d/181RokW2JoTkveVXhTLCyS6OkcJ2apd08vR2WP7gY6zk/edit?userstoinvite=gracie.atkins@gmail.com&ts=59409828&actionButton=1#gid=2051220756

One option is the Approved 2016/2017 Budget report:
https://assets.austintexas.gov/budget/16-17/downloads/Approved_Volume_1_FINAL.pdf
_This is a good document for reference and context about each department, but its a PDF. And the manual process of extracting data from this document is hard and uncertain._

Another option is through the Open Data portal. There are a couple dataset that seem relevant, but this one was most interesting. A filtered view of the Raw Budget vs. Expense that filters for only "General Fund." 
https://data.austintexas.gov/resource/e622-gceg
_This seems very promising, but it requires processing with a script. That is what I started playing with tonight in Ruby. I started cross-checking calculations recorded in the PDF report with Grace._

The last option we've identified is the one you call out @sya.
https://www.austintexas.gov/financeonline/finance/budget/department.cfm
The limitation of this data (at least on the landing page) is that departments are broken into even smaller operating groups than we have them categorized in Budget Party. We based our categorization of the Office of Performance Management. In order to get the right number, we would have to do some merging and processing, similar to what is required in the raw Socrata dataset.

Anyways, hopeful that something comes out of the call with Public Works @sya.

**Comment by mateoclarke** [comment]
Ok, summing up the work I started tonight. Here is the ruby script that grabs data from `data.austintexas.gov` loops through a discrete list of Departments, requests all their line items in the General Fund, and sums them up, and prints it out.

Here is a link to the code:
https://gist.github.com/mateoclarke/931d0a3fdebb845d1caab86566b7b0fd

Here is the output for the 5 departments I added so far:
```
Municipal Court 2016-2017 Budget from General Fund: 22,514,014
  from 709 line item records.
Animal Services 2016-2017 Budget from General Fund: 12,914,285
  from 361 line item records.
Fire 2016-2017 Budget from General Fund: 189,013,831
  from 1,483 line item records.
Austin Public Library 2016-2017 Budget from General Fund: 47,167,036
  from 743 line item records.
Austin Public Health 2016-2017 Budget from General Fund: 38,536,285
  from 1,845 line item records.
```

**Comment by VictoriaODell** [comment]
This was done for our budget game night with the help of Ashley Fisher from Austin Monitor.
