### ISSUE TITLE
[Aug 1] Gigabit Community Fund Deadline

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#206]
## Latinitas
- Latinitas is taking the lead on submitting an application to get Budget Party curriculum adopted and modified for thier clubs.
- Leads on our side: @VictoriaODell @secmorris
- #171 

## Cross-city adoption for Eugene, OR
- Robert and his counterpart in Oregon connected us to Chris & Daniel who might be interested in collaborating on making Budget Party work in their City.
- setting up an intro call is pending
> Chris Sjoblom (CC'd) and his group (mostly from local org IDX Brokers) are heading a Public Participation platform here in Eugene and were interested in using the work he and his team have done as part of a Hack-a-Thon to increase civic participation in Eugene - and has partnered with the Eugene Chamber of Commerce and have participated in City Council meetings.
> Daniel Brian Keith of Quantum Clay has previously worked on a Eugene Community Dashboard and has heavy interest in data journalism. I have no doubt Daniel would be a great addition were a local "Open Eugene" chapter to emerge.

**Comment by VictoriaODell** [comment]
Hey @mateoclarke. Spoke with Latinitas today and they don't have a current POA for adding gigabyte functionality into what we have and I know I don't have the bandwidth to ideate or execute on that with what we currently have either. 

I know we discussed the call/conferencing but it seemed based on their call they don't have a wide enough audience to need that functionality since they are primarily doing work on the East side and coordinating something new would mean going into some unknown territory (which we did with the Austin Monitor.) 

Robert expressed concern to them on another call and said we/BP should probably be leading the discussion on funding and gigabyte functionality but that's not something I can commit to despite the deadline extension. 

It seems like we are not a good fit/not ready for this round but should keep Latinitas in the civic tech/open Austin/ Budget Party loop. 

I pushed them to check out Fake the News again and we might need to reconnect them directly to Sarah Morris. Sarah mentioned previously that Fake the News seems like a pretty natural fit for the org and I think some collaboration can happen there without forcing Gigabyte into the conversation since that project was funded differently. This, of course, is up to Sarah though.

**Comment by mateoclarke** [comment]
What is POA?

**Comment by mateoclarke** [comment]
Regardless, I agree. If they can't lead the effort in classrooms and if they aren't a good use case for Gigabit internet, passing for now seems like the right choice. Have you spoken with Robert directly about it? It is probably a good time to check in with him at least via Slack if you haven't.

**Comment by VictoriaODell** [comment]
@mateoclarke POA= Plan of action 

And sure thing! 

Also posting the Eugene notes here: https://docs.google.com/document/d/1OYpcO3e09JH877RZT-2Wh6jwPSY9i0-qgIMd_SsgtpA/edit?usp=sharing

**Comment by mateoclarke** [comment]
Thanks for taking time for the call today @VictoriaODell. It feels like we haven't been getting wins recently on this project, but I think we are doing the right thing to take it slow so we can recharge and regroup for another sprint later in the year.

**Comment by secmorris** [comment]
Thanks for the updates @VictoriaODell and @mateoclarke  I apologize for being late to the party - that AISD stuff really ate into my week. 

I'd be very happy to reconnect with Latinitas about Fake News. They're actually the third group that's spoken to me about adapting the curriculum for a younger audience. I feel like there might be some momentum there that's worth exploring! 

I agree with Mateo about taking it slow with BP. And at least there are upcoming Gigabit opportunities that we can explore. 

Just an FYI I've been diving into the BP curriculum and have some ideas I'll share out.

**Comment by VictoriaODell** [comment]
This passed.
