### ISSUE TITLE
General Feedback from 8/16 budget game night

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/budgetparty#66]
_Starting a list of things overheard or observed as folks were working through the app last night..._
- Judging page `/results` should show change by percentage for each group
- One team didn't realize you could tap the buttons several times. How could we animate, add language, or create some signaling that invites to user to tap several times
- More context for departments. One group pointed out that the Transportation Department amount looked low. That was because ATD gets money from other places than the General Fund. Knowing that is helpful context for understanding where department gets funding.
- One group asked how to submit once they were done, maybe rename "Report" in the nav to "Submit" or "Finish"?
- Seeing a percent of total budget by department would be helpful. _(Made up example: Police get 40% of total General Fund)_
- Someone asked if the $969 M number was the rollup amount for the General Fund. I didn't know what that means.

**Comment by colbywhite** [comment]
- One of the judges mentioned there were some unrealistic aspects to the app. The one I remember the most was the fact that the city has contracts with certain groups - the police department for example - so how much money gets allocated to them is written in stone and can't be changed. Trying to show all that while continuing to keep the design simple and digestible might be a challenge, but a worthwhile one.
- I thought @VictoriaODell's idea of having the department's boxes have an expandable/collapsable drawer (or something) to display more information on the department (like the tradeoff info) was a good one.

**Comment by mateoclarke** [comment]
_This budget game tool is easy to use!  I wonder if it could be enhanced to allow users to adjust fees (water, electric, wastewater, etc.) to see how that impacts the budget.  We need a “SimBudget” tool like SimCity so user can see the impact that budget increases or decreases have on services._

**Comment by VictoriaODell** [comment]
Doing the data entry from the paper survey 
[Paper Nano Survey Results digitized
](https://docs.google.com/document/d/1QVfMPeN0lQRE40tyyUQpzPZRtjjldpOwiKKfQMJ9eGc/edit#)

**Comment by VictoriaODell** [comment]
From issue #67 

"Really great stuff, I'm impressed. Looks solid, and it's nice and fast. Some thoughts:

way too much needless information. Is there a reason the user needs to know the exact number of civil servants employed by the budget? Onboarding page is like so many other civic websites, over saturated with text. That same info can be gotten across more concisely and more visually.
So the bottom bar is basically preceded through sequentially. Some kind of signifier for which one you are would be good. Additionally as it is basically sequential, some kind of numbering or sequence signifier would be good. Doesn't have to be numbers, could be a range of colors, but something to help indicated passage over time.
Love the illustrations on the services main page. Really smart. Actually would like to see this throughout the entire app more. This would help bring personality and I think help differentiate the groupings better.
Nice job separating the different sub categories into cards, but I feel they need something slightly more. Maybe a shadow to help them stick off the page (like the card system in Material Design https://material.google.com/components/cards.html )or something like that. The illustrations would also help as I said.
current buttons for increasing or decreasing the budget aren't bad, but I think they need to have more directionality to them. Doesn't have to be arrows, could also be something like a half circle shape or something else like that. It also needs an active click state so that when you click you know that you clicked it, not just that you see the numbers go up. More feed back is good. Also the severity of the increment should be indicated not only through the numbers but color. I would think that having a solid button color for the 1% and a ghost color button for the .1% would work, or a gradation of color (light red versus deep red, yellowish green versus bluish green)
More interactivity to the visualizations would be a nice touch. Being able to see an increasing bar graph or a growing circle, really anything besides just numbers would make a big difference for usability.
I feel like the margin underneath "spending" is a little too large. It has a 10px margin on top and bottom, but since Spending is a headline for what goes under it, the amount of money, it should be more like 10px on top, and 2-5px on bottom, so that those two are more visually grouped. This general problem actually pops up in several other places, like "Your Budget" and a couple of other titles.
Looks really slick and works fast though! I like it. Very cool."

**Comment by mateoclarke** [comment]
This feedback from the v0 prototype has been incorporated into the v1 designs
